"""One-off ingestion script for hard Expression of Ideas questions (Reading & Writing)."""
from __future__ import annotations
import json
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from ingestion.embed import embed_batch
from ingestion.load import get_collection

QUESTIONS = [
    {
        "id": "4e564c4f",
        "question_text": 'With its clichéd imagery of suburban lawns and power lines, John Ashbery\'s 2004 poem "Ignorance of the Law Is No Excuse" may seem barren terrain for critical analysis. ______ cultural critic Lauren Berlant finds fertile ground in just its first two stanzas, devoting most of a book chapter to deciphering the "weight of the default space" Ashbery creates in this poem.\n\nWhich choice completes the text with the most logical transition?',
        "choices": ["A) Likewise,", "B) Nonetheless,", "C) In turn,", "D) That is,"],
        "correct_answer": "B",
        "explanation": '"Nonetheless" indicates disagreement — the first sentence calls the poem "barren terrain" for analysis, while the second says Berlant found "fertile ground," a direct contradiction. Choice A (likewise) signals similarity, not contrast. Choice C (in turn) signals cause-and-effect, which doesn\'t fit. Choice D (that is) signals restatement, but the second sentence contradicts rather than restates the first.',
        "domain": "Expression of Ideas",
        "skill": "Transitions",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "d3888864",
        "question_text": "While researching a topic, a student has taken the following notes:\n• The National Congress of American Indians (NCAI) was founded in 1944 by representatives of fifty tribal governments.\n• The NCAI was created to protect the sovereignty of Indigenous tribes.\n• Napoleon B. Johnson (Cherokee) was the NCAI's first president.\n• In 1975, the US Congress passed the Indian Self-Determination and Education Assistance Act (Public Law 96-638).\n• This legislation formally acknowledged tribes' right to self-governance.\n• The advocacy of the NCAI was a key factor in the law's passing.\n\nThe student wants to identify an accomplishment of the NCAI. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
        "choices": [
            "A) The NCAI, founded by representatives of fifty tribal governments, had Napoleon B. Johnson (Cherokee) as its first president.",
            "B) Founded in 1944, the NCAI was created by representatives of tribal governments from fifty sovereign Indigenous tribes.",
            "C) The NCAI's advocacy was key to the passing of Public Law 96-638, legislation formally acknowledging Indigenous tribes' right to self-governance.",
            "D) In 1975, the NCAI passed the Indian Self-Determination and Education Assistance Act, which was created to protect the sovereignty of Indigenous tribes.",
        ],
        "correct_answer": "C",
        "explanation": "Choice C directly identifies an accomplishment: the NCAI's advocacy was key to passing Public Law 96-638, which formally acknowledged Indigenous tribes' right to self-governance. Choice A describes founding and first president — not an accomplishment. Choice B describes the founding — not an accomplishment. Choice D misrepresents the notes: the US Congress, not the NCAI, passed the act.",
        "domain": "Expression of Ideas",
        "skill": "Rhetorical Synthesis",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "29f5d8bd",
        "question_text": "While researching a topic, a student has taken the following notes:\n• In 1978, Sámi activists staged protests to block the construction of a dam on the Alta River in Norway.\n• The dam would disrupt Sámi fishing and reindeer herding.\n• The dam was ultimately built, but the Alta conflict had a lasting impact.\n• It brought international attention to the issue of Sámi rights.\n• It led to a set of 2005 legal protections establishing Sámi rights to lands, waters, and resources.\n\nThe student wants to make and support a generalization about the Alta conflict. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
        "choices": [
            "A) During the Alta conflict, Sámi activists staged protests to block the construction of a dam on the Alta River in Norway that would disrupt local fishing and reindeer herding.",
            "B) Although the dam that the Sámi activists had protested was ultimately built, the Alta conflict had a lasting impact.",
            "C) Sámi rights to lands, waters, and resources received international attention and legal protections as a result of the Alta conflict.",
            "D) The Alta conflict had a lasting impact, resulting in international attention and legal protections for Sámi rights to lands, waters, and resources.",
        ],
        "correct_answer": "D",
        "explanation": "Choice D makes a generalization (the conflict had a lasting impact) and supports it with evidence (attention and protections resulted from it). Choice A describes a specific event, not a generalization. Choice B makes a generalization but doesn't support it. Choice C makes a statement about the aftermath without adequately supporting the generalization — it's also too specific.",
        "domain": "Expression of Ideas",
        "skill": "Rhetorical Synthesis",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "59aa305b",
        "question_text": "While researching a topic, a student has taken the following notes:\n• Ulaanbaatar is the capital of Mongolia.\n• The city's population is 907,802.\n• Ulaanbaatar contains 31.98 percent of Mongolia's population.\n• Hanoi is the capital of Vietnam.\n• The city's population is 7,781,631.\n• Hanoi contains 8.14 percent of Vietnam's population.\n\nThe student wants to emphasize the relative sizes of the two capitals' populations. Which choice most effectively uses information from the given sentences to emphasize the relative sizes of the two capitals' populations?",
        "choices": [
            "A) Mongolia's capital is Ulaanbaatar, which has 907,802 people, and Vietnam's capital is Hanoi, which has 7,781,631 people.",
            "B) Comparing Vietnam and Mongolia, 7,781,631 is 8.14 percent of Vietnam's population, and 907,802 is 31.98 percent of Mongolia's.",
            "C) Even though Hanoi (population 7,781,631) is larger than Ulaanbaatar (population 907,802), Ulaanbaatar accounts for more of its country's population.",
            "D) The populations of the capitals of Mongolia and Vietnam are 907,802 (Ulaanbaatar) and 7,781,631 (Hanoi), respectively.",
        ],
        "correct_answer": "C",
        "explanation": "Choice C emphasizes relative sizes by noting that even though Hanoi has more people overall, Ulaanbaatar accounts for a larger percentage of its country's population. Choices A and D only state raw population figures without comparing them relative to each other or to country populations. Choice B emphasizes country population sizes and fails to mention the capitals.",
        "domain": "Expression of Ideas",
        "skill": "Rhetorical Synthesis",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "dffab2d7",
        "question_text": "While researching a topic, a student has taken the following notes:\n• African American women played prominent roles in the Civil Rights Movement, including at the famous 1963 March on Washington.\n• Civil rights activist Anna Hedgeman, one of the march's organizers, was a political adviser who had worked for President Truman.\n• Civil rights activist Daisy Bates was a well-known journalist and advocate for school desegregation.\n• Hedgeman worked behind the scenes to make sure a woman was included in the lineup of speakers at the march.\n• Bates was the sole woman to speak, delivering a brief but memorable address to the cheering crowd.\n\nThe student wants to compare the two women's contributions to the March on Washington. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
        "choices": [
            "A) Hedgeman and Bates contributed to the march in different ways; Bates, for example, delivered a brief but memorable address.",
            "B) Hedgeman worked in politics and helped organize the march, while Bates was a journalist and school desegregation advocate.",
            "C) Although Hedgeman worked behind the scenes to make sure a woman speaker was included, Bates was the sole woman to speak at the march.",
            "D) Many African American women, including Bates and Hedgeman, fought for civil rights, but only one spoke at the march.",
        ],
        "correct_answer": "C",
        "explanation": "Choice C compares both women's contributions to the march: Hedgeman worked behind the scenes to ensure a woman speaker was included, whereas Bates actually spoke at the event. Choice A doesn't indicate what Hedgeman did, so no comparison is made. Choice B doesn't mention Bates's contribution to the march. Choice D doesn't compare their individual contributions to the march.",
        "domain": "Expression of Ideas",
        "skill": "Rhetorical Synthesis",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "990bd995",
        "question_text": "While researching a topic, a student has taken the following notes:\n• A thermal inversion is a phenomenon where a layer of atmosphere is warmer than the layer beneath it.\n• In 2022, a team of researchers studied the presence of thermal inversions in twenty-five gas giants.\n• Gas giants are planets largely composed of helium and hydrogen.\n• The team found that gas giants featuring a thermal inversion were also likely to contain heat-absorbing metals.\n• One explanation for this relationship is that these metals may reside in a planet's upper atmosphere, where their absorbed heat causes an increase in temperature.\n\nThe student wants to present the study's findings to an audience already familiar with thermal inversions. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
        "choices": [
            "A) Heat-absorbing metals may reside in a planet's upper atmosphere.",
            "B) The team studied thermal inversions in twenty-five gas giants, which are largely composed of helium and hydrogen.",
            "C) Researchers found that gas giants featuring a thermal inversion were likely to contain heat-absorbing metals, which may reside in the planets' upper atmospheres.",
            "D) Gas giants were likely to contain heat-absorbing metals when they featured a layer of atmosphere warmer than the layer beneath it, researchers found; this phenomenon is known as a thermal inversion.",
        ],
        "correct_answer": "C",
        "explanation": "Choice C describes the study's findings in a way that assumes familiarity with thermal inversions — it uses the term without defining it. Choice A doesn't include anything about thermal inversions. Choice B doesn't describe the study's findings. Choice D defines thermal inversion, which would be unnecessary for an already-familiar audience.",
        "domain": "Expression of Ideas",
        "skill": "Rhetorical Synthesis",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "9dcc184d",
        "question_text": 'Plato believed material objects to be crude representations of unseen ideal forms. In his view, such abstract, nonmaterial forms are the ultimate source of knowledge. Aristotle disagreed, positing that knowledge is best obtained through direct engagement with the material world; ______ sensory experience of the material is the ultimate source of knowledge.\n\nWhich choice completes the text with the most logical transition?',
        "choices": ["A) regardless,", "B) admittedly,", "C) in other words,", "D) meanwhile,"],
        "correct_answer": "C",
        "explanation": '"In other words" signals that the claim about sensory experience is a restatement of Aristotle\'s theory from earlier in the sentence. Choice A (regardless) illogically suggests the claim is true in spite of Aristotle\'s theory. Choice B (admittedly) illogically suggests an exception to his theory. Choice D (meanwhile) illogically signals a separate, simultaneous idea rather than a restatement.',
        "domain": "Expression of Ideas",
        "skill": "Transitions",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "aba812aa",
        "question_text": "While researching a topic, a student has taken the following notes:\n• Nissologists are scientists who study islands.\n• Some nissologists define an island as any piece of land surrounded by water.\n• Using that definition, they determined that Sweden has 221,000 islands.\n• Other nissologists define an island as being 1 kilometer square, a certain distance from the mainland, and having at least 50 permanent residents.\n• Using that definition, they determined that Sweden has 24 islands.\n\nThe student wants to make and support a generalization about nissologists' definition of an island. Which choice most effectively uses relevant information from the notes to accomplish these goals?",
        "choices": [
            "A) The definition of an island as any piece of land surrounded by water is supported by some nissologists, scientists who study islands.",
            "B) Multiple counts of Sweden's islands have been based on different definitions of an island.",
            "C) Based on a recent count, Sweden has a relatively small number of islands with at least 50 permanent residents.",
            "D) Nissologists' different definitions can result in huge disparities in counts of islands, as the example of Sweden shows.",
        ],
        "correct_answer": "D",
        "explanation": "Choice D makes a generalization (different definitions cause huge disparities in island counts) and supports it with the example of Sweden (221,000 vs. 24 islands). Choice A introduces one definition without making a generalization. Choice B is about Sweden's counts without making a generalization about definitions. Choice C makes an inference about Sweden without mentioning nissologists' definitions.",
        "domain": "Expression of Ideas",
        "skill": "Rhetorical Synthesis",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "33a93756",
        "question_text": 'In the late twentieth century, scholars directed much discussion toward issues of spatiality. Adherents to quantitative analytical approaches delineated space with the use of GIS spatial technologies; ______ cultural geographer Doreen Massey defined space as the product of "an ever-shifting social geometry of power and signification," focusing instead on socio-political forces.\n\nWhich choice completes the text with the most logical transition?',
        "choices": ["A) for example,", "B) by contrast,", "C) as such,", "D) likewise,"],
        "correct_answer": "B",
        "explanation": '"By contrast" signals that Massey\'s socio-political focus contrasts with the quantitative/GIS approaches described in the previous clause. Choice A (for example) would imply Massey exemplifies the quantitative approach, which is wrong. Choice C (as such) implies her approach is a result of the quantitative approach. Choice D (likewise) implies her approach is similar, which is the opposite of what the text shows.',
        "domain": "Expression of Ideas",
        "skill": "Transitions",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "f99639a1",
        "question_text": "When one looks at the dark craggy vistas in Hitoshi Fugo's evocative photo series, one's mind might wander off to the cratered surfaces of faraway planets. ______ it's the series' title, Flying Frying Pan, that brings one back to Earth, reminding the viewer that each photo is actually a close-up view of a familiar household object: a frying pan.\n\nWhich choice completes the text with the most logical transition?",
        "choices": ["A) Consequently,", "B) Alternatively,", "C) Ultimately,", "D) Additionally,"],
        "correct_answer": "C",
        "explanation": '"Ultimately" (meaning "in the end" or "eventually") fits because the first sentence describes the initial experience of imagining other planets, and the second describes what happens afterward — the title brings the viewer back to reality. Choice A (consequently) implies the imagining caused the title to act, which is wrong. Choice B (alternatively) implies an option, but both experiences happen in sequence. Choice D (additionally) implies agreement, but the experiences are opposite.',
        "domain": "Expression of Ideas",
        "skill": "Transitions",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "c6b6128f",
        "question_text": "Seismologists Kaiqing Yuan and Barbara Romanowicz have proposed that the magma fueling Iceland's more than 30 active volcano systems emerges from deep within Earth. The great depths involved—nearly 3,000 km—mark Iceland's volcanoes as extreme outliers; ______ many of Earth's volcanoes are fed by shallow pockets of magma found less than 15 km below the surface.\n\nWhich choice completes the text with the most logical transition?",
        "choices": ["A) indeed,", "B) nevertheless,", "C) in addition,", "D) consequently,"],
        "correct_answer": "A",
        "explanation": '"Indeed" signals elaboration on the same underlying idea — that Iceland\'s deep-magma volcanoes are outliers, which is confirmed by the fact that most volcanoes use shallow magma. Choice B (nevertheless) is a disagreement transition, but both parts agree. Choice C (in addition) signals a new idea, but the second clause elaborates on the first. Choice D (consequently) implies cause-and-effect, but Iceland\'s deep magma doesn\'t cause other volcanoes to use shallow pockets.',
        "domain": "Expression of Ideas",
        "skill": "Transitions",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "1572e3e1",
        "question_text": "While researching a topic, a student has taken the following notes:\n• As engineered structures, many bird nests are uniquely flexible yet cohesive.\n• A research team led by Yashraj Bhosale wanted to better understand the mechanics behind these structural properties.\n• Bhosale's team used laboratory models that simulated the arrangement of flexible sticks into nest-like structures.\n• The researchers analyzed the points where sticks touched one another.\n• When pressure was applied to the model nests, the number of contact points between the sticks increased, making the structures stiffer.\n\nThe student wants to present the primary aim of the research study. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
        "choices": [
            "A) Bhosale's team wanted to better understand the mechanics behind bird nests' uniquely flexible yet cohesive structural properties.",
            "B) The researchers used laboratory models that simulated the arrangement of flexible sticks and analyzed the points where sticks touched one another.",
            "C) After analyzing the points where sticks touched, the researchers found that the structures became stiffer when pressure was applied.",
            "D) As analyzed by Bhosale's team, bird nests are uniquely flexible yet cohesive engineered structures.",
        ],
        "correct_answer": "A",
        "explanation": "Choice A directly states why the team conducted the study — its primary aim: to understand the mechanics behind bird nests' structural properties. Choice B describes the methodology (how the study was done), not the aim. Choice C describes a result, not the aim. Choice D makes a general observation about bird nests without presenting the study's aim.",
        "domain": "Expression of Ideas",
        "skill": "Rhetorical Synthesis",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "8f3ad8e1",
        "question_text": "Modernista architects championed nature in their designs. ______ the wavy staircase and ornate floral tilework of Hospital de Sant Pau, a Modernista hospital designed by Lluís Domènech i Montaner, couldn't exactly grow in a forest. Still, one sees natural influences in Domènech i Montaner's penchant for curves (rather than right angles) and plant- and animal-inspired flourishes.\n\nWhich choice completes the text with the most logical transition?",
        "choices": ["A) Furthermore,", "B) Similarly,", "C) Of course,", "D) Thus,"],
        "correct_answer": "C",
        "explanation": '"Of course" signals an obvious qualification — acknowledging that while Modernista architects championed nature, their designs couldn\'t literally grow in a forest. This concedes an obvious limitation before the text circles back to affirm the natural influence. Choice A (furthermore) just adds information. Choice B (similarly) implies similarity with the first sentence. Choice D (thus) implies the hospital\'s features are a result of championing nature, which misreads the structure.',
        "domain": "Expression of Ideas",
        "skill": "Transitions",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "867ceff8",
        "question_text": "The Sun and other stars are powered by nuclear fusion reactions, in which two atoms collide to form a single heavier atom, releasing energy. Scientists have long believed that fusion has the potential to meet humanity's clean energy needs. ______ prior to December 2022, no fusion reaction in a laboratory setting had ever generated a net energy gain.\n\nWhich choice completes the text with the most logical transition?",
        "choices": ["A) For this reason,", "B) Moreover,", "C) Specifically,", "D) That said,"],
        "correct_answer": "D",
        "explanation": '"That said" signals a contradiction between scientists\' optimistic belief in fusion\'s potential and the reality that no lab reaction had achieved net energy gain. Choice A (for this reason) implies cause-and-effect — the failure would be caused by the belief, which makes no sense. Choice B (moreover) adds a supporting point, but failing to achieve net gain doesn\'t support fusion\'s potential. Choice C (specifically) introduces an example of the belief, but this sentence contradicts the optimism.',
        "domain": "Expression of Ideas",
        "skill": "Transitions",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "cd75bd44",
        "question_text": 'While researching a topic, a student has taken the following notes:\n• The popular wood-wide web theory posits that trees can communicate and exchange resources with one another via common mycorrhizal networks (CMNs) of fungi.\n• Ecologist Dr. Suzanne Simard first suggested this theory in 1997.\n• She described trees as "super-cooperators."\n• In the 2022 study "The Decay of the Wood-Wide Web?," mycologist Dr. Justine Karst and colleagues evaluated dozens of CMN studies.\n• They write that CMNs "have captured the interest of broad audiences. We are concerned, however, that recent claims about CMNs in forests are disconnected from evidence."\n\nThe student wants to use a quotation to emphasize a potential problem with the wood-wide web theory. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
        "choices": [
            'A) Describing trees as "super-cooperators," Simard first suggested that trees can exchange resources with one another in 1997.',
            'B) In "The Decay of the Wood-Wide Web?," Karst and colleagues note that common mycorrhizal networks "have captured the interest of broad audiences."',
            'C) After evaluating dozens of CMN studies, Karst and colleagues expressed concern that recent claims about common mycorrhizal networks are "disconnected from evidence."',
            'D) Despite the concerns expressed in the 2022 study "The Decay of the Wood-Wide Web?," the wood-wide web theory remains popular.',
        ],
        "correct_answer": "C",
        "explanation": 'Choice C uses a quotation ("disconnected from evidence") to convey the authors\' criticism — a potential problem with the theory. Choice A uses a quotation to introduce the theory, not criticize it. Choice B uses a quotation about the theory\'s broad appeal, not its problem. Choice D doesn\'t use a quotation at all.',
        "domain": "Expression of Ideas",
        "skill": "Rhetorical Synthesis",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "21f19050",
        "question_text": 'While researching a topic, a student has taken the following notes:\n• In 1971, experimental musician Pauline Oliveros created Sonic Meditations.\n• Sonic Meditations is not music but rather a series of sound-based exercises called meditations.\n• Each meditation consists of instructions for participants to make, imagine, listen to, or remember sounds.\n• The instructions for Meditation V state, "walk so silently that the bottoms of your feet become ears."\n• Those for Meditation XVIII state, "listen to a sound until you no longer recognize it."\n\nThe student wants to provide an explanation and an example of Oliveros\'s Sonic Meditations. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
        "choices": [
            'A) Sonic Meditations is not music but rather a series of sound-based meditations that consist of instructions; Meditation XVIII, for instance, instructs participants to "listen to a sound until you no longer recognize it."',
            "B) In 1971, Oliveros created Sonic Meditations, a series of meditations that consist of instructions for participants to make, imagine, listen to, or remember sounds.",
            'C) "Walk so silently that the bottoms of your feet become ears" is one example of the instructions found in Oliveros\'s Sonic Meditations.',
            'D) While both meditations consist of instructions, Meditation XVIII instructs participants to "listen," whereas Meditation V instructs participants to "walk."',
        ],
        "correct_answer": "A",
        "explanation": "Choice A both explains what Sonic Meditations is (a series of sound-based meditations consisting of instructions) and gives an example (Meditation XVIII). Choice B explains what it is but gives no example. Choice C gives an example but doesn't explain what Sonic Meditations is. Choice D doesn't describe what Sonic Meditations is.",
        "domain": "Expression of Ideas",
        "skill": "Rhetorical Synthesis",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "9579edb4",
        "question_text": "Magnetic levitation (maglev) trains are suspended above a track by powerful electromagnets, reducing friction and thus allowing for much faster speeds. Though maglev advocates in the US have long imagined these trains crisscrossing the country, their dream remains unrealized. ______ of the handful of maglev trains currently in operation, all are in Asia.\n\nWhich choice completes the text with the most logical transition?",
        "choices": ["A) In fact,", "B) To that end,", "C) Nevertheless,", "D) That said,"],
        "correct_answer": "A",
        "explanation": '"In fact" emphasizes how far maglev advocates\' dreams are from reality — all existing maglev trains are in Asia, strengthening the point that the US dream is unrealized. Choice B (to that end) implies cause-and-effect. Choices C and D (nevertheless, that said) are disagreement transitions, but this sentence agrees with and strengthens the previous one.',
        "domain": "Expression of Ideas",
        "skill": "Transitions",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "c5423706",
        "question_text": "In a heated debate in biogeography, the field is divided between dispersalists and vicariancists. ______ there are those who argue that dispersal is the most crucial determining factor in a species' distribution, and those who insist that vicariance (separation due to geographic barriers) is. Biogeographer Isabel Sanmartín counts herself among neither.\n\nWhich choice completes the text with the most logical transition?",
        "choices": ["A) Furthermore,", "B) By contrast,", "C) Similarly,", "D) That is,"],
        "correct_answer": "D",
        "explanation": '"That is" signals that this sentence clarifies the terms of the debate introduced in the previous sentence — it explains what dispersalists and vicariancists are. Choice A (furthermore) implies additional, separate information. Choice B (by contrast) implies a contrast, but the second sentence clarifies, not contradicts. Choice C (similarly) implies similarity, which doesn\'t fit a clarification.',
        "domain": "Expression of Ideas",
        "skill": "Transitions",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "5efdc098",
        "question_text": 'In Asiya Wadud\'s 2022 poem "Shorn, Treaded Red," the poet contemplates a painting that has inspired her: Etel Adnan\'s 2020 work Satellites 27. The painting, which features overlapping geometric shapes, fuels the poem\'s exploration of temporality and identity. ______ in responding to Adnan\'s artwork, Wadud\'s poem reflects on the relationship between poetry and other art forms.\n\nWhich choice completes the text with the most logical transition?',
        "choices": ["A) In other words,", "B) For instance,", "C) What's more,", "D) Conversely,"],
        "correct_answer": "C",
        "explanation": '"What\'s more" introduces an additional aspect of the poem beyond what was discussed — the reflection on poetry\'s relationship to other art forms is separate from and additional to the exploration of temporality and identity. Choice A (in other words) implies restatement. Choice B (for instance) implies the second claim is an example of the first. Choice D (conversely) implies contradiction.',
        "domain": "Expression of Ideas",
        "skill": "Transitions",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "bcb73490",
        "question_text": "While researching a topic, a student has taken the following notes:\n• Neuroscientists Krishnan Padmanabhan and Zhen Chen sought to better understand the workings of the brain's olfactory system.\n• They devised a study using mathematical models.\n• They found that certain fibers allow the brain to toggle from one method of processing smells to another.\n• In one method, cells in the piriform cortex (where the perception of odor forms) capture olfactory information at a given moment.\n• In the other, the cells track changes in olfactory information over time.\n\nThe student wants to summarize the study's findings. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
        "choices": [
            "A) To arrive at these findings, which describe dual methods of processing smells in the piriform cortex, Padmanabhan and Chen devised a study using mathematical models.",
            "B) Padmanabhan and Chen showed that olfactory information is captured by cells in the piriform cortex, where the perception of odor forms.",
            "C) Using mathematical models, Padmanabhan and Chen devised a study to better understand the workings of the brain's olfactory system.",
            "D) According to Padmanabhan and Chen, the brain can toggle between capturing olfactory information at a given moment and tracking changes in that information over time.",
        ],
        "correct_answer": "D",
        "explanation": "Choice D summarizes the findings: the brain can toggle between two methods — capturing olfactory information at a given moment and tracking changes over time. Choice A focuses on methodology, not findings. Choice B notes one fact about the olfactory system without summarizing the key finding about toggling. Choice C presents the study's goal, not its findings.",
        "domain": "Expression of Ideas",
        "skill": "Rhetorical Synthesis",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "e261a81f",
        "question_text": "While researching a topic, a student has taken the following notes:\n• The Million Song Dataset (MSD) includes main audio features and descriptive tags for popular songs.\n• Audio features include acoustic traits such as loudness and pitch intervals.\n• Many algorithms use these audio features to predict a new song's popularity.\n• These algorithms may fail to accurately identify main audio features of a song with varying acoustic traits.\n• Algorithms based on descriptive tags that describe fixed traits such as genre are more reliable predictors of song popularity.\n\nThe student wants to explain a disadvantage of relying on audio features to predict a song's popularity. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
        "choices": [
            "A) Many popularity-predicting algorithms are based on a song's audio features, such as loudness and pitch intervals.",
            "B) Algorithms based on audio features may misidentify the main features of a song with varying acoustic traits, making such algorithms less reliable predictors of popularity than those based on fixed traits.",
            "C) Audio features describe acoustic traits such as pitch intervals, which may vary within a song, whereas descriptive tags describe fixed traits such as genre, which are reliable predictors of popularity.",
            "D) The MSD's descriptive tags are reliable predictors of a song's popularity, as the traits they describe are fixed.",
        ],
        "correct_answer": "B",
        "explanation": "Choice B explains the disadvantage: audio-feature algorithms may misidentify features in songs with varying acoustic traits, making them less reliable than fixed-trait algorithms. Choice A states a fact without evaluating reliability. Choice C describes the difference between audio features and tags without explaining why this matters as a disadvantage. Choice D focuses on tags, not the disadvantage of audio features.",
        "domain": "Expression of Ideas",
        "skill": "Rhetorical Synthesis",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "0a6b66b3",
        "question_text": "In 1815, while in exile in Jamaica, Venezuelan revolutionary Simón Bolívar penned a letter praising England's republican government and expressing hope that Latin American nations seeking independence from Spain might achieve something similar. The letter was addressed to a local merchant, Henry Cullen; ______ though, Bolívar's goal was to persuade political leaders from England and Europe to support his cause.\n\nWhich choice completes the text with the most logical transition?",
        "choices": ["A) additionally,", "B) ultimately,", "C) accordingly,", "D) consequently,"],
        "correct_answer": "B",
        "explanation": '"Ultimately" means "in the long run" or "at the highest level." Although Bolívar wrote to a local merchant, his ultimate goal was to reach political leaders in Europe. The contrast word "though" also signals tension between the letter\'s stated recipient and its real audience. Choice A (additionally) implies agreement, but the ideas contrast. Choices C and D (accordingly, consequently) imply cause-and-effect, which doesn\'t fit.',
        "domain": "Expression of Ideas",
        "skill": "Transitions",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "afc8b561",
        "question_text": "While researching a topic, a student has taken the following notes:\n• British scholar Robert Plot described fossilized dinosaur bones in his 1676 book The Natural History of Oxfordshire.\n• Plot earned a reputation for being the first person to have discovered dinosaur remains.\n• In 1990, archaeologists in Lesotho, in southern Africa, discovered a fossilized phalanx of a Massospondylus carinatus dinosaur in a cave once inhabited by humans.\n• Indigenous Khoesan and Basotho peoples had inhabited the cave beginning around 1100 CE.\n• According to paleontologist Julien Benoit, these peoples may have found the phalanx and brought it to the cave centuries before Plot's descriptions.\n\nThe student wants to emphasize the significance of the 1990 discovery to Plot's reputation. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
        "choices": [
            "A) Benoit challenged Plot's reputation for being the first person to have discovered M. carinatus remains.",
            "B) Evidence that Khoesan and Basotho peoples may have found an M. carinatus phalanx as long ago as 1100 CE suggests that Plot may not have been the first person to have discovered dinosaur remains.",
            "C) According to Benoit's analysis of the 1990 discovery, Indigenous peoples in southern Africa may have brought the fossilized phalanx to the cave as long ago as 1100 CE.",
            "D) In 1990, more than three centuries after Plot claimed in his book that he had found fossilized dinosaur bones, archaeologists uncovered evidence in southern Africa that disproved his claims.",
        ],
        "correct_answer": "B",
        "explanation": "Choice B emphasizes the significance to Plot's reputation: evidence that Indigenous peoples may have found dinosaur remains in 1100 CE suggests Plot was not first. Choice A misrepresents the notes — Plot was reputed to be first to discover dinosaur remains generally, not M. carinatus specifically. Choice C only partially explains the significance without tying it to Plot's reputation. Choice D misrepresents the notes — the discovery challenged Plot's reputation as first discoverer, not the validity of his claims.",
        "domain": "Expression of Ideas",
        "skill": "Rhetorical Synthesis",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "6be089ec",
        "question_text": "A 2017 study of sign language learners tested the role of iconicity—the similarity of a sign to the thing it represents—in language acquisition. The study found that the greater the iconicity of a sign, the more likely it was to have been learned. ______ the correlation between acquisition and iconicity was lower than that between acquisition and another factor studied: sign frequency.\n\nWhich choice completes the text with the most logical transition?",
        "choices": ["A) In fact,", "B) In other words,", "C) Granted,", "D) As a result,"],
        "correct_answer": "C",
        "explanation": '"Granted" signals that the following information — iconicity isn\'t as strongly correlated with acquisition as sign frequency — is true in spite of the previous finding about iconicity\'s correlation with learning. Choice A (in fact) implies emphasis or refutation, neither of which fits. Choice B (in other words) implies restatement, but this sentence adds new information. Choice D (as a result) implies iconicity\'s correlation caused the frequency comparison, which makes no sense.',
        "domain": "Expression of Ideas",
        "skill": "Transitions",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "9db9a861",
        "question_text": 'While researching a topic, a student has taken the following notes:\n• Digital Light Synthesis (DLS) is a form of additive manufacturing that utilizes light to rapidly cure liquid resin into high-quality, 3D objects.\n• Step 1: Ultraviolet (UV) light images are projected up into a pool of liquid resin, where the object\'s first layer takes shape.\n• Step 2: The partially cured resin object is raised, leaving a thin space (a "dead zone") beneath it for oxygen and liquid resin to flow through.\n• Step 3: The UV light passes through the dead zone—maintaining the flow of resin—and partially cures additional layers of the object.\n• Step 4: When the resin object is complete, it is baked in an oven to complete the curing.\n\nThe student wants to describe how DLS cures 3D objects. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
        "choices": [
            'A) DLS is a form of additive manufacturing that creates a "dead zone" in which UV light solidifies layer by layer before being baked in an oven, creating a high-quality, 3D object.',
            'B) DLS cures 3D objects by passing through a "dead zone," adding layers to the object, then curing the object in an oven.',
            "C) In DLS, UV light images are projected into a liquid resin pool to cure a 3D object layer by layer; once solidified, the object is baked in an oven.",
            'D) In DLS, UV light is projected into layers of liquid resin until the resin solidifies and passes through a "dead zone," wherein the curing is completed.',
        ],
        "correct_answer": "C",
        "explanation": "Choice C accurately describes the process: UV light is projected into liquid resin to cure the object layer by layer, then the object is baked in an oven to complete curing. Choice A misrepresents — it implies the UV light (not the object) is baked. Choice B misrepresents — DLS, not UV light, passes through the dead zone. Choice D misrepresents — it suggests already-solidified resin passes through the dead zone and curing is completed there, but actually liquid resin flows through while UV light cures layers, and final curing happens in the oven.",
        "domain": "Expression of Ideas",
        "skill": "Rhetorical Synthesis",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "a2941bd8",
        "question_text": 'Iraqi artist Nazik Al-Malaika, celebrated as the first Arabic poet to write in free verse, didn\'t reject traditional forms entirely; her poem "Elegy for a Woman of No Importance" consists of two ten-line stanzas and a standard number of syllables. Even in this superficially traditional work, ______ Al-Malaika was breaking new ground by memorializing an anonymous woman rather than a famous man.\n\nWhich choice completes the text with the most logical transition?',
        "choices": ["A) therefore,", "B) in fact,", "C) moreover,", "D) though,"],
        "correct_answer": "D",
        "explanation": '"Though" provides the contrast needed between the traditional form of the poem and the groundbreaking subject matter — even while using traditional structure, Al-Malaika was innovating thematically. Choice A (therefore) signals cause-and-effect, which doesn\'t fit. Choice B (in fact) emphasizes the previous statement, but the text needs contrast. Choice C (moreover) adds a supporting point, but the text needs contrast, not addition.',
        "domain": "Expression of Ideas",
        "skill": "Transitions",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "d600f35e",
        "question_text": "While researching a topic, a student has taken the following notes:\n• Some powerful works of literature have so influenced readers that new legislation has been passed as a result.\n• The Interesting Narrative of the Life of Olaudah Equiano (1789) is the autobiography of a man who endured slavery on both sides of the Atlantic.\n• Equiano's book contributed to the passage of the Slave Trade Act of 1807.\n• The Jungle (1906) is a fictional work by Upton Sinclair that describes unsanitary conditions in US meatpacking plants.\n• Sinclair's book contributed to the passage of the Pure Food and Drug Act in 1906.\n\nThe student wants to emphasize a difference between the two books. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
        "choices": [
            "A) Although both are powerful works of literature that contributed to new legislation, Equiano's book is an autobiography, while Sinclair's is fictional.",
            "B) They may have written about different topics, but Equiano and Sinclair both influenced readers.",
            "C) The 1807 Slave Trade Act resulted in part from a book by Equiano, while the 1906 Pure Food and Drug Act resulted in part from a book by Sinclair.",
            "D) The Interesting Narrative of the Life of Olaudah Equiano and The Jungle are two works of literature that contributed to new legislation (concerning the slave trade and food safety, respectively).",
        ],
        "correct_answer": "A",
        "explanation": "Choice A emphasizes a difference (genre: autobiography vs. fiction) while acknowledging a similarity. Choice B mentions different topics but emphasizes the similarity of influencing readers. Choice C notes different laws but reflects similarity (both resulted in legislation) without emphasizing a meaningful difference. Choice D emphasizes similarity — both contributed to new legislation.",
        "domain": "Expression of Ideas",
        "skill": "Rhetorical Synthesis",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "004680af",
        "question_text": "While researching a topic, a student has taken the following notes:\n• Freddie Wong (born 1985) is a director and special effects artist from the United States.\n• He is best known for the action-comedy web series Video Game High School (VGHS).\n• VGHS premiered in 2012 on RocketJump, a YouTube channel that Wong cocreated.\n• The series was celebrated for its inventive video game–centric world and high-quality special effects.\n• VGHS was nominated for a Producers Guild Award for Outstanding Digital Series.\n\nThe student wants to begin a narrative about Wong's award-nominated web series. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
        "choices": [
            "A) In 2012, director and visual effects artist Freddie Wong launched a new action-comedy web series: Video Game High School.",
            "B) Video Game High School was celebrated for its inventive video game–centric world and high-quality special effects, and it was nominated for a Producer's Guild Award for Outstanding Digital Series.",
            "C) Wong, cocreator of the YouTube channel RocketJump, would go on to see his web series be nominated for a Producers Guild Award.",
            "D) In 2012, Video Game High School premiered on RocketJump; it would later be nominated for an award.",
        ],
        "correct_answer": "A",
        "explanation": "Choice A begins the narrative effectively by introducing Wong and VGHS to an unfamiliar audience, establishing the time, creator, and genre. Choice B jumps to the end (awards and reception) without explaining what VGHS is. Choice C doesn't name the web series and jumps ahead in the story. Choice D doesn't explain what VGHS is and doesn't mention Wong.",
        "domain": "Expression of Ideas",
        "skill": "Rhetorical Synthesis",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "857346cd",
        "question_text": "The Madison is a type of line dance that involves neat rows of dancers performing a repeated sequence of steps in unison. ______ many other dances are also defined by order, repetition, and synchronicity, but the Madison is distinguished by its extreme uniformity; when an auditorium full of dancers performs the Madison, one almost gets the impression of a military march.\n\nWhich choice completes the text with the most logical transition?",
        "choices": ["A) However,", "B) Of course,", "C) Specifically,", "D) Moreover,"],
        "correct_answer": "B",
        "explanation": '"Of course" signals an obvious similarity — acknowledging that other dances share order, repetition, and synchronicity — before the sentence goes on to highlight the Madison\'s distinguishing extreme uniformity. Choice A (however) implies the information about other dances contrasts with the Madison description, when it actually acknowledges a similarity. Choice C (specifically) implies the information elaborates on the Madison. Choice D (moreover) implies addition to the Madison\'s description.',
        "domain": "Expression of Ideas",
        "skill": "Transitions",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "38a981d0",
        "question_text": 'While researching a topic, a student has taken the following notes:\n• Archaeologist Jon Erlandson and colleagues argue that humans first arrived in the Americas by sea.\n• They propose that humans traveled between Pacific Ocean islands and coastlines from northeast Asia to the Americas.\n• Many of these islands and coastal zones were later submerged as glaciers melted and sea levels rose.\n• The researchers think that "a coastal route, including kelp forests and estuaries, would have provided a rich mix of marine, estuarine, riverine, and terrestrial resources" such as seaweeds, fish, and birds.\n• This proposed scenario is known as the kelp highway hypothesis.\n\nThe student wants to summarize the kelp highway hypothesis. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
        "choices": [
            'A) Pacific Ocean islands and coastlines likely contained "a rich mix of marine, estuarine, riverine, and terrestrial resources" such as seaweeds, fish, and birds, according to researchers.',
            "B) One argument about how humans first arrived in the Americas is the kelp highway hypothesis proposed by Jon Erlandson and colleagues.",
            "C) Humans may have first arrived in the Americas by sea, traveling between Pacific Ocean islands and coastlines and subsisting on a variety of resources.",
            "D) As glaciers melted and sea levels rose, many Pacific Ocean islands and coastal zones were submerged.",
        ],
        "correct_answer": "C",
        "explanation": "Choice C summarizes the hypothesis at a high level: humans may have arrived in the Americas by sea, traveling island to island along coastlines and using available resources. Choice A describes one aspect (resources available) but doesn't discuss human migration. Choice B names the hypothesis but doesn't explain what it entails. Choice D describes the geological aftermath but doesn't discuss human migration.",
        "domain": "Expression of Ideas",
        "skill": "Rhetorical Synthesis",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "781e8f5c",
        "question_text": "While researching a topic, a student has taken the following notes:\n• Two opposing theories of vision divided scholars for many centuries.\n• The ancient Greek mathematician Euclid (circa 300 BCE) supported the extramission theory.\n• This theory held that the eyes emit a form of radiation that illuminates objects in its range.\n• The ancient Greek philosopher Aristotle (384–322 BCE) supported the intromission theory.\n• This theory held that objects emit a form of radiation that reaches the eyes.\n• In the eleventh century, Arab mathematician Ibn al-Haytham (965–1040 CE) largely settled the debate with the first conclusive experiments supporting intromission.\n\nThe student wants to provide a historical overview of the two theories. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
        "choices": [
            "A) Scholars were divided between the extramission and intromission theories of vision until Ibn al-Haytham's eleventh-century experiments largely settled the debate in support of intromission.",
            "B) Through two opposing theories of vision—extramission and intromission—Euclid, Aristotle, and Ibn al-Haytham held that a form of radiation is emitted either from objects or from the eyes.",
            "C) While Ibn al-Haytham largely settled the debate in the eleventh century, Aristotle supported the theory of intromission centuries before.",
            "D) Before the eleventh century, the ancient Greek philosopher Aristotle supported the intromission theory, which held that objects emit a form of radiation that reaches the eyes.",
        ],
        "correct_answer": "A",
        "explanation": "Choice A provides a historical overview of both theories — scholars were divided between extramission and intromission until Ibn al-Haytham's experiments largely settled it. Choice B identifies both theories and scholars but doesn't give a historical overview of how the debate evolved. Choice C mentions only intromission and doesn't mention extramission. Choice D only covers intromission theory.",
        "domain": "Expression of Ideas",
        "skill": "Rhetorical Synthesis",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "5bb70279",
        "question_text": '"Tulip mania"—the rapid rise and sudden fall of the price of tulip bulbs in seventeenth-century Amsterdam—is often cited as an example of the perils of rampant market speculation. However, recent research has demonstrated that the episode was neither as frenzied nor as disastrous as has been thought. The popular myth surrounding it, ______ should be regarded with some skepticism.\n\nWhich choice completes the text with the most logical transition?',
        "choices": ["A) for example,", "B) by contrast,", "C) nevertheless,", "D) therefore,"],
        "correct_answer": "D",
        "explanation": '"Therefore" is a cause-and-effect transition: because recent research has shown tulip mania was not as disastrous as thought (the cause), the popular myth should be viewed with skepticism (the effect). Choice A (for example) implies skepticism is an example of the research, which misreads the logic. Choices B and C (by contrast, nevertheless) are disagreement transitions, but this sentence follows logically from the previous one rather than contradicting it.',
        "domain": "Expression of Ideas",
        "skill": "Transitions",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "b8582018",
        "question_text": 'While researching a topic, a student has taken the following notes:\n• In a 2023 study, environmental scientist Jazmin Locke-Rodriguez and colleagues tested the use of floating treatment wetlands (FTWs) in Florida.\n• FTWs are artificial floating platforms of plants used to remediate polluted or nutrient-imbalanced water.\n• Finding: FTWs using marigold flowers removed 52% more total phosphorus than the control.\n• Finding: The test yielded 65 market-quality blooms per square meter.\n• The authors concluded marigolds showed "promising potential as a commercially viable remediating crop cultivated on FTWs in South Florida."\n\nThe student wants to present the findings of the study. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
        "choices": [
            'A) The authors concluded that marigolds grown on FTWs were "commercially viable," having produced 65 blooms per square meter of market-quality blooms in a 2023 study.',
            "B) In a 2023 study, Locke-Rodriguez and colleagues found that marigolds cultivated on FTWs produced 52% more market-quality flower blooms than the control.",
            "C) Locke-Rodriguez and colleagues found that FTWs using marigolds not only helped remove phosphorus from the water but also yielded market-quality blooms.",
            "D) FTWs using marigolds, Locke-Rodriguez and colleagues found, yielded 65 flower blooms and removed 52% of phosphorus from the water.",
        ],
        "correct_answer": "C",
        "explanation": "Choice C presents both findings: marigolds removed phosphorus and yielded market-quality blooms. Choice A presents only the bloom finding and omits the phosphorus finding. Choice B misrepresents — the 52% figure refers to phosphorus removed vs. control, not bloom yield. Choice D misrepresents — the marigolds removed 52% more phosphorus than the control, not 52% of total phosphorus, and the bloom count was 65 per square meter.",
        "domain": "Expression of Ideas",
        "skill": "Rhetorical Synthesis",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "c9ecaf7d",
        "question_text": "While researching a topic, a student has taken the following notes:\n• One of history's greatest libraries was the House of Wisdom in Baghdad, Iraq.\n• It was founded in the eighth century with the goal of preserving all the world's knowledge.\n• Scholars at the House of Wisdom collected ancient and contemporary texts from Greece, India, and elsewhere and translated them into Arabic.\n• Writings included those of the Greek philosopher Aristotle and the Indian mathematician Aryabhata.\n• The House of Wisdom used Chinese papermaking technology to create paper versions to be studied and shared.\n\nThe student wants to explain how the House of Wisdom preserved the world's knowledge. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
        "choices": [
            "A) The House of Wisdom was known for bringing together knowledge from around the world, including from Greece, India, and China.",
            "B) Founded in Iraq in the eighth century, the House of Wisdom employed many scholars as translators.",
            "C) Writings from the Greek philosopher Aristotle and the Indian mathematician Aryabhata were preserved at the House of Wisdom.",
            "D) The House of Wisdom collected writings from different countries and created paper versions in Arabic to be studied and shared.",
        ],
        "correct_answer": "D",
        "explanation": "Choice D explains the how: collecting writings from different countries, translating them into Arabic, and creating paper versions to be studied and shared. Choice A says the library brought together knowledge but doesn't explain the mechanism. Choice B mentions scholars as translators but doesn't explain the full preservation process. Choice C identifies two specific authors but doesn't explain how the library preserved knowledge.",
        "domain": "Expression of Ideas",
        "skill": "Rhetorical Synthesis",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "0d9560e0",
        "question_text": 'While researching a topic, a student has taken the following notes:\n• Phobetor, a name drawn from Greek mythology, is an exoplanet that orbits the star PSR B1257+12, also known as Lich.\n• Phobetor\'s mass is 0.01 times that of Jupiter, or 0.01 Jupiter masses.\n• Mastika, which means "gem" or "jewel" in Malay, is an exoplanet that orbits the star HD 179949, also known as Gumala.\n• Mastika\'s mass is 0.92 Jupiter masses.\n\nThe student wants to make and support a generalization about exoplanets. Which choice most effectively uses relevant information from the notes to accomplish this goal?',
        "choices": [
            "A) Exoplanets that are named Phobetor orbit Lich, and those that are named Mastika orbit Gumala.",
            "B) Even though Phobetor and Mastika are both exoplanets, their masses are different: Phobetor's mass is 0.01 Jupiter masses, and Mastika's is 0.92 Jupiter masses.",
            'C) Many stars have both a designation and a proper name; for instance, PSR B1257+12 is also known as Lich, and HD 179949 is also known as Gumala.',
            'D) Exoplanet names have diverse origins, a fact that can be seen in the cases of Phobetor, a name drawn from Greek mythology, and Mastika, which means "gem" or "jewel" in Malay.',
        ],
        "correct_answer": "D",
        "explanation": 'Choice D makes a generalization (exoplanet names have diverse origins) and supports it with examples (Phobetor from Greek mythology; Mastika meaning "gem" in Malay). Choice A misrepresents the notes by implying multiple exoplanets share each name. Choice B contrasts two specific exoplanets\' masses without making a generalization about exoplanets broadly. Choice C makes a generalization about stars, not exoplanets.',
        "domain": "Expression of Ideas",
        "skill": "Rhetorical Synthesis",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
    {
        "id": "140d2d15",
        "question_text": "While researching a topic, a student has taken the following notes:\n• Stars form in a galaxy when gravity causes a massive cloud of dust and gas to collapse.\n• A galaxy in a phase of rapid star formation is called a starburst galaxy.\n• Quenching is a process in which a galaxy loses star-forming gas.\n• A galaxy that no longer forms stars is called a quenched galaxy.\n• A quenched galaxy has entered the poststarburst phase.\n\nThe student wants to explain what a quenched galaxy is. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
        "choices": [
            "A) Before quenching, a starburst galaxy will form stars at a rapid rate.",
            "B) When it becomes quenched, a starburst galaxy enters the poststarburst phase.",
            "C) Having entered the poststarburst phase, a quenched galaxy is one that no longer forms stars.",
            "D) A starburst galaxy will lose star-forming gas and eventually become quenched.",
        ],
        "correct_answer": "C",
        "explanation": "Choice C defines a quenched galaxy — one that has entered the poststarburst phase and no longer forms stars. Choice A only describes what happens before quenching (rapid star formation). Choice B only describes what happens after quenching (entering poststarburst phase) without defining the term. Choice D describes what causes quenching (losing star-forming gas) without defining what a quenched galaxy is.",
        "domain": "Expression of Ideas",
        "skill": "Rhetorical Synthesis",
        "difficulty": "Hard",
        "calculator_allowed": None,
        "source": "EQB",
        "image_path": None,
    },
]


def main():
    print(f"Embedding {len(QUESTIONS)} questions…")
    embed_batch(QUESTIONS)

    jsonl_path = "data/structured/expression_of_ideas_hard.jsonl"
    with open(jsonl_path, "w", encoding="utf-8") as f:
        for q in QUESTIONS:
            f.write(json.dumps(q, ensure_ascii=False) + "\n")
    print(f"Saved {jsonl_path}")

    collection = get_collection()
    ids, embeddings, documents, metadatas = [], [], [], []
    for q in QUESTIONS:
        ids.append(q["id"])
        embeddings.append(q["embedding"])
        documents.append(q["question_text"])
        metadatas.append({
            "domain": q["domain"],
            "skill": q["skill"],
            "difficulty": q["difficulty"],
            "source": q["source"],
            "correct_answer": q["correct_answer"],
            "choices": json.dumps(q["choices"]),
            "explanation": q["explanation"],
            "calculator_allowed": q.get("calculator_allowed") or "",
            "image_path": q.get("image_path") or "",
        })

    collection.upsert(ids=ids, embeddings=embeddings, documents=documents, metadatas=metadatas)
    print(f"Collection now has {collection.count()} total records.")


if __name__ == "__main__":
    main()
